create table public.radar_entries (
  id bigint generated by default as identity primary key,
  name text not null,
  ring text not null check (ring in ('Adopt','Trial','Assess','Hold')),
  sector text not null check (sector in ('Physical','Intellectual','Emotional','Social','Spiritual','Vocational','Financial','Environmental')),
  is_new boolean not null default false,
  description text not null default '',
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (sector, name)
);

alter table public.radar_entries enable row level security;
grant select on table public.radar_entries to anon, authenticated;
create policy "Radar entries are publicly readable"
on public.radar_entries for select to anon, authenticated using (true);
create index radar_entries_display_order_idx
on public.radar_entries (display_order, sector, ring);
